import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export const exportToInvoice = (expenses: any[]) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(59, 130, 246); // Blue color
  doc.text('EXPENSE INVOICE', 20, 20);
  
  // Company Info
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Finance ERP System', 20, 35);
  doc.text('Business Expense Report', 20, 45);
  doc.text(`Generated: ${format(new Date(), 'MMMM dd, yyyy')}`, 20, 55);
  
  // Summary
  const total = expenses.reduce((sum, expense) => sum + expense.amount, 0);
  doc.setFontSize(14);
  doc.setTextColor(59, 130, 246);
  doc.text(`Total Amount: $${total.toFixed(2)}`, 20, 70);
  doc.text(`Total Transactions: ${expenses.length}`, 20, 80);
  
  // Table
  const tableData = expenses.map(expense => [
    expense.description,
    expense.category,
    format(new Date(expense.date), 'MMM dd, yyyy'),
    `$${expense.amount.toFixed(2)}`,
    expense.notes || '-'
  ]);
  
  autoTable(doc, {
    startY: 90,
    head: [['Description', 'Category', 'Date', 'Amount', 'Notes']],
    body: tableData,
    theme: 'grid',
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    headStyles: {
      fillColor: [59, 130, 246],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { cellWidth: 30 },
      2: { cellWidth: 30 },
      3: { cellWidth: 25, halign: 'right' },
      4: { cellWidth: 40 },
    },
  });
  
  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text(`Page ${pageCount}`, 20, doc.internal.pageSize.height - 10);
  doc.text('Generated by Finance ERP System', 120, doc.internal.pageSize.height - 10);
  
  // Save the PDF
  doc.save(`expense-invoice-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
};